config/routes.rb
Rails.application.routes.draw do
	root "puzzles#index"
	
	resources :puzzles do
		resources :comments
		resources :constraints
	end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :puzzle
	
	validates :nick, presence: true
	validates :body, presence: true
end

app/models/constraint.rb
class Constraint < ApplicationRecord
	serialize :array, Array
	belongs_to :puzzle
end

app/models/puzzle.rb
class Puzzle < ApplicationRecord
	serialize :grid, Array
	
	has_many :comments, dependent: :destroy
	has_many :constraints, dependent: :destroy
	
	validates :title, presence: true
	validates :rules, presence: true, length: {minimum: 10}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
    @puzzle = Puzzle.find(params[:puzzle_id])
    @comment = @puzzle.comments.create(comment_params)
    redirect_to puzzle_path(@puzzle)
  end
	
	def destroy
    @puzzle = Puzzle.find(params[:puzzle_id])
    @comment = @puzzle.comments.find(params[:id])
    @comment.destroy
    redirect_to puzzle_path(@puzzle), status: :see_other
  end
	
  private
    def comment_params
      params.require(:comment).permit(:nick, :body)
    end
end

app/controllers/puzzles_controller.rb
class PuzzlesController < ApplicationController
  def index
		@puzzles = Puzzle.all
  end
	
	def show
		@puzzle = Puzzle.find(params[:id])
	end
	
	def new
		@puzzle = Puzzle.new
	end
	
	def create
		@puzzle = Puzzle.new(puzzle_params)
		
		if @puzzle.save
			redirect_to @puzzle
		else
			render :new, status: :unprocessable_entity
		end
	end
	
	def edit
		@puzzle = Puzzle.find(params[:id])
	end
	
	def update
		@puzzle = Puzzle.find(params[:id])
		
		if @puzzle.update(puzzle_params)
			redirect_to @puzzle
		else
			render :new, status: :unprocessable_entity
		end
	end
	
	def destroy
		@puzzle = Puzzle.find(params[:id])
		@puzzle.destroy
		
		redirect_to root_path, status: :see_other
	end
	
	private
		def puzzle_params
			params.require(:puzzle).permit(:title, :rules, :rows, :cols)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/puzzles_helper.rb
module PuzzlesHelper
end

app/views/comments/_comment.html.erb
<p>
  <strong><%= comment.nick %>: </strong>
	<%= comment.body %>
</p>

app/views/comments/_form.html.erb
<%= form_with model: [ @puzzle, @puzzle.comments.build ] do |form| %>
  <p>
    <%= form.label :nick %><br>
    <%= form.text_field :nick %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PuzzleApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
		
		<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
		
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/puzzles/_form.html.erb
<%= form_with model: puzzle do |form| %>
	<div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
		<% puzzle.errors.full_messages_for(:title).each do |message| %>
      <div class="error"><%= message + "."%></div>
    <% end %>
  </div>
	
  <div>
    <%= form.label :rules %><br>
    <%= form.text_area :rules %>
		<% puzzle.errors.full_messages_for(:rules).each do |message| %>
      <div class="error"><%= message + "." %></div>
    <% end %>
  </div>
	
	<div>
		<%= form.label :rows, "# rows" %>
		<%= form.number_field :rows, value: 9, in: 4...20 %>
			
	</div>
		
	<div>
		<%= form.label :cols, "# columns" %>
		<%= form.number_field :cols, value: 9, in: 4...20 %>
	</div>
	
  <div>
    <%= form.submit %>
  </div>
<% end %>

<!-- doesn't work for new, assuming the reason could be with not yet saved instance -->
<% if not newHtml %>
	<%= render "puzzle", puzzle: puzzle %>
<% end %>

app/views/puzzles/_puzzle.html.erb
<div class="board">
	<div class="grid">
		<div class="cells">
			<% for i in 0...puzzle.rows do %>
				<div class="rowX">
					<% for j in 0...puzzle.cols do %>
						<div class="cell">
							<%= puzzle.grid[i*9 + j] %> 
						</div>
					<% end %>
				</div>
			<% end %>
		</div>
		
		
		<%	rowLen = 64*puzzle.rows
				colLen = 64*puzzle.cols %>
		<svg class= "boardSvg" width="<%= colLen %>" height="<%= rowLen %>">
			<!-- outline grid -->
			<rect width="<%= colLen %>" height="<%= rowLen %>" class="gridStyle"/>
			
			<!-- if 9x9 -->
			<% if puzzle.rows == 9 && puzzle.cols == 9 %>
				<% boxSize = 64*3 %>
				<% for i in 0...3 do %>
					<% for j in 0...3 do %>
						<rect width="<%= boxSize %>" height="<%= boxSize %>" x="<%= boxSize*i %>" y="<%=boxSize*j %>" class="gridStyle"/>
					<% end %>
				<% end %>
			<% end %>
		</svg>	
		
		
	</div>
</div>

app/views/puzzles/edit.html.erb
<h1>Edit puzzle</h1>

<%= render "form", puzzle: @puzzle, newHtml: false %>

app/views/puzzles/index.html.erb
<h1>List of puzzles</h1>

<ul>
	<% @puzzles.each do |puzzle| %>
		<li>
			<%= link_to puzzle.title, puzzle %>
		</li>	
	<% end %>
</ul>

<%= link_to "Set a new puzzle", new_puzzle_path %>

app/views/puzzles/new.html.erb
<h1>New puzzle</h1>

<%= render "form", puzzle: @puzzle, newHtml: true %>

<%= link_to "Back to menu", root_path %>

app/views/puzzles/show.html.erb
<div class="info">
	<h1><%= @puzzle.title %></h1>
	<p><%= @puzzle.rules %></p>
</div>

<%= render "puzzle", puzzle: @puzzle %>

<ul>
	<li><%= link_to "Edit", edit_puzzle_path(@puzzle) %></li>
	<li><%= link_to "Delete puzzle", puzzle_path(@puzzle), data:{
					turbo_method: :delete, turbo_confirm: "Do you really want to delete the puzzle?"} %></li>
	<li><%= link_to "Back to menu", root_path %></li>
</ul>

<h2>Comments</h2>
<%= render @puzzle.comments %>

<h2>Add a comment:</h2>
<%= render "comments/form" %>